adding go teal compile option changes
algorand/generator pull request #37
Opened 2022-07-12 16:39 UTC by barnjamin

This is done in order to pass a GET parameter through the Go client for TEAL compile endpoint

2022-07-12 20:33 UTC, Eric-Warehime approved these changes

2022-07-13 01:33 UTC, michaeldiamant approved these changes
@barnjamin Thanks for finding a way forward here.  ☕ 

* I confirmed the generated changes produce _no_ diff with https://github.com/algorand/go-algorand-sdk/pull/335 as of https://github.com/algorand/go-algorand-sdk/pull/335/commits/2c673b256b64f3bd84058c94b48bc8f28d873c64.
* Out of scope to the PR:  I opened an issue because it feels to me that a more robust solution is warranted - https://github.com/algorand/generator/issues/38.

2022-07-13 11:02 UTC, winder requested changes
We shouldn't add special cases in new endpoints. The special cases elsewhere were done for backwards compatibility and will be removed in a future major release.

2022-07-13 13:18 UTC, winder commented on go_templates/query.vm
> +#if ( $queryType == "TealCompile")
You need something like
```#if ( $q.method == "post" )
#set( $verb = "post" )
#else if (  $q.method == "post" )
#set( $verb = "get" )
#else
UNHANDLED HTTP METHOD: $q.method
##$unknown.type ## force a template failure with an unknown type
#end
```

Then you can use $verb when calling the helper function.


For the dependency, wrap it in a local helper like we do with post/get. That you don't can avoid adding a conditional import.

2022-07-13 13:20 UTC, barnjamin commented on go_templates/query.vm
> +#if ( $queryType == "TealCompile")
I don't quite understand

The request generated is still a POST method but the URL needs to include the parameter.

2022-07-20 13:40 UTC, michaeldiamant approved these changes
As of https://github.com/algorand/generator/pull/37/commits/c5fb80f83dcb14c682e2cdf02be6510e14599e2d and as expected, I confirmed re-generating Go SDK produces no diffs in https://github.com/algorand/go-algorand-sdk/pull/335.

2022-07-20 16:18 UTC, michaeldiamant commented
Merging - Based on a verbal with @winder, we agreed I can merge provided I'm comfortable with the diff.

2022-07-20 16:18 UTC, merged